go:
  - changed-files:
      - any-glob-to-any-file:
          - src/**
          - main.go
          - go.mod
          - go.sum

shell:
  - changed-files:
      - any-glob-to-any-file:
          - shell/**

bash:
  - changed-files:
      - any-glob-to-any-file:
          - shell/**/*.bash

zsh:
  - changed-files:
      - any-glob-to-any-file:
          - shell/**/*.zsh

fish:
  - changed-files:
      - any-glob-to-any-file:
          - shell/**/*.fish

vim:
  - changed-files:
      - any-glob-to-any-file:
          - plugin/**

docs:
  - changed-files:
      - any-glob-to-any-file:
          - '*.md'
          - doc/**
          - man/**

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**

build:
  - changed-files:
      - any-glob-to-any-file:
          - Makefile
          - .goreleaser.yml
          - Dockerfile

test:
  - changed-files:
      - any-glob-to-any-file:
          - test/**
          - src/**/*_test.go

install:
  - changed-files:
      - any-glob-to-any-file:
          - install
          - install.ps1
          - uninstall
