Layout/LineLength:
  Enabled: false
Metrics:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
    - assert
    - exit
    - paste
    - puts
    - raise
    - refute
    - require
    - send_keys
  IgnoredPatterns:
    - ^assert_
    - ^refute_
Style/NumericPredicate:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/WordArray:
  MinSize: 1
Minitest/AssertEqual:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
