FROM centos:centos7
MAINTAINER Junegunn Choi <junegunn.c@gmail.com>

# yum
RUN yum install -y git gcc make tar ncurses-devel

# Install Go 1.4
RUN cd / && curl \
    https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz | \
    tar -xz && mv go go1.4

ENV GOPATH /go
ENV GOROOT /go1.4
ENV PATH /go1.4/bin:$PATH

# Volume
VOLUME /go

# Default CMD
CMD cd /go/src/github.com/junegunn/fzf/src && /bin/bash

